# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7acdab3d4f3fa886978f1efec8e969f8129b9335decc316df3cc3330d9e1a11942885b51543d680c4801a91c0d474a7f659d1840a473f03776992577bc4ecac6

test:
  secret_key_base: ac2e8544698c729b36e99d3f32ad9e922f10018d3e12b6bf63ee5e6184f4ec3f2670c649d73af6da1a89fb2178f3970d4b7c7eaf76160958f015caa9193cab89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9acdab3d4f3fa886978f1efec8e969f8129b9335decc316df3cc3330d9e1a11942885b51543d680c4801a91c0d474a7f659d1840a473f03776992577bc4ecac6
  
